#!/bin/sh

PRIVATE_LOCATION=/var/packages/EynioConnect/target
PIDFILE=/var/run/eynio.pid

start_package()
{
    HOME=/var/packages/EynioConnect/etc node ${PRIVATE_LOCATION}/server.js --nocolor --pidfile $PIDFILE --platform Synology &> /var/log/eynio.log &
}

stop_package()
{
    if [ -f $PIDFILE ]; then
        /bin/kill $(cat $PIDFILE)
        rm $PIDFILE
    fi
}

case $1 in
	start)
		start_package
                exit 0
                ;;
        stop)
                stop_package
                exit 0
                ;;
        status)
                if [ -f $PIDFILE ]; then
                    exit 0
                else
                    exit 1
                fi
                ;;
        killall)
                stop_package
                exit 0
                ;;
        log)
                echo "/var/log/eynio.log"
                exit 0
                ;;
esac
